<?php

namespace App\General;

class SupportedLanguages
{

    public const Languages = [
            'Algeria'              => 'ar',
            'Argentina'            => 'es',
            'Australia'            => 'en',
            'Austria'              => 'de',
            'Bahrain'              => 'ar',
            'Belgium'              => 'fr',
            'Bolivia'              => 'es',
            'Brazil'               => 'pt',
            'Cameroon'             => 'fr',
            'Canada'               => 'en',
            'Caribbean'            => 'en',
            'Chile'                => 'es',
            'China'                => 'zh',
            'Colombia'             => 'es',
            'Congo'                => 'fr',
            'Costa Rica'           => 'es',
            'Cote d\'Invoire'      => 'fr',
            'Dominican Republic'   => 'es',
            'Ecuador'              => 'es',
            'Egypt'                => 'ar',
            'El Salvador'          => 'es',
            'France'               => 'fr',
            'Germany'              => 'de',
            'Great Britain'        => 'en',
            'Guatemala'            => 'es',
            'Honduras'             => 'es',
            'Hong Kong'            => 'zh',
            'India'                => 'hi',
            'Iraq'                 => 'ar',
            'Ireland'              => 'en',
            'Italy'                => 'it',
            'Jamaica'              => 'en',
            'Japan'                => 'ja',
            'Jordan'               => 'ar',
            'Kuwait'               => 'ar',
            'Lebanon'              => 'ar',
            'Libya'                => 'ar',
            'Liechtenstein'        => 'de',
            'Luxembourg'           => 'fr',
            'Macau SAR'            => 'zh',
            'Mali'                 => 'fr',
            'Mexico'               => 'es',
            'Moldova'              => 'ru',
            'Monaco'               => 'fr',
            'Morocco'              => 'fr',
            'Netherlands'          => 'nl',
            'New Zealand'          => 'en',
            'Nicaragua'            => 'es',
            'Oman'                 => 'ar',
            'Panama'               => 'es',
            'Paraguay'             => 'es',
            'Peru'                 => 'es',
            'Portugal'             => 'pt',
            'Puerto Rico'          => 'es',
            'Qatar'                => 'ar',
            'Russia'               => 'ru',
            'Saudi Arabia'         => 'ar',
            'Senegal'              => 'fr',
            'Singapore'            => 'zh',
            'South Africa'         => 'en',
            'South Korea'          => 'ko',
            'Spain'                => 'es',
            'Switzerland'          => 'fr',
            'Syria'                => 'ar',
            'Taiwan'               => 'zh',
            'Trinidad'             => 'en',
            'Tunisia'              => 'ar',
            'United Arab Emirates' => 'ar',
            'United States'        => 'en',
            'Uruguay'              => 'es',
            'Venezuela'            => 'es',
            'West Indies'          => 'fr',
            'Yemen'                => 'ar',
            'Zimbabwe'             => 'en',
    ];
}
