name: Auto Label (add labels to PR based on matched file RegEx)

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  auto-label:
    name: Auto Label PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: banyan/auto-label@1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
