name: Label approved pull requests (PR)

on: pull_request_review

jobs:
  labelWhenApproved:
    name: Label PR when approved
    runs-on: ubuntu-latest
    steps:
      - name: Label PR when approved
        uses: pullreminders/label-when-approved-action@master
        env:
          APPROVALS: "2"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
          REMOVE_LABEL: "awaiting%20review"
